"""all tables

Revision ID: 133ac9529464
Revises: f9a5fc9c0c65
Create Date: 2022-12-08 13:59:06.721138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133ac9529464'
down_revision = 'f9a5fc9c0c65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
